# Generated by Django 2.2.19 on 2021-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_auto_20210329_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoavoto',
            name='quantidade_votos',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Quantidade de Votos:'),
        ),
    ]
