# Generated by Django 2.2.19 on 2021-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_pessoavoto_quantidade_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoavoto',
            name='quantidade_votos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Votos:'),
        ),
    ]
