# Generated by Django 2.2.19 on 2021-03-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_auto_20210329_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoavoto',
            options={'verbose_name': 'Votação:', 'verbose_name_plural': 'Votações:'},
        ),
        migrations.AlterModelTable(
            name='pessoavoto',
            table='PessoaVoto',
        ),
    ]
