# Generated by Django 2.2.19 on 2021-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcaovoto',
            options={'verbose_name': 'OpcaoVoto', 'verbose_name_plural': 'OpcoesVoto'},
        ),
        migrations.AlterField(
            model_name='votacao',
            name='anonimo',
            field=models.BooleanField(default=False, verbose_name='Características da eleição'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='voto_unico',
            field=models.BooleanField(default=False, verbose_name='Voto unico'),
        ),
    ]
