# Generated by Django 2.2.19 on 2021-03-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210324_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcaovoto',
            options={'verbose_name': 'OpçãoVoto', 'verbose_name_plural': 'OpcoesVoto'},
        ),
        migrations.AlterModelOptions(
            name='votacao',
            options={'verbose_name': 'Votação', 'verbose_name_plural': 'Votações'},
        ),
        migrations.AlterModelTable(
            name='votacao',
            table='Votação',
        ),
    ]
