# Generated by Django 2.2.19 on 2021-03-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20210324_1811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opcaovoto',
            table='OpcaoVoto',
        ),
    ]
