# Generated by Django 2.2.19 on 2021-03-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210324_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcaovoto',
            options={'verbose_name': 'Opção Voto', 'verbose_name_plural': 'Opções de Voto'},
        ),
        migrations.AlterModelTable(
            name='votacao',
            table='Votacao',
        ),
    ]
