# Generated by Django 2.2.19 on 2021-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20210324_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='codigo',
            field=models.CharField(max_length=1000, verbose_name='Código eleição:'),
        ),
        migrations.AlterField(
            model_name='opcaovoto',
            name='num_votos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de votos:'),
        ),
    ]
