# Generated by Django 2.2.19 on 2021-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20210329_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='codigo',
            field=models.PositiveSmallIntegerField(max_length=1000, verbose_name='Código eleição:'),
        ),
    ]
