# Generated by Django 2.2.19 on 2021-03-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_auto_20210329_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='codigo',
            field=models.PositiveSmallIntegerField(verbose_name='Código eleição:'),
        ),
    ]
