# Generated by Django 2.2.19 on 2021-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20210329_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='codigo',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Código eleição:'),
        ),
    ]
